spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://124.220.154.222:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 124.220.154.222:8848
  application:
    name: gulimall-product

mybatis-plus:
  mapper-locations:  classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 18000


logging:
  level:
    com.atguigu.gulimall: debug

alibaba:
  cloud:
    access-key: LTAI5t9HsdbWiGnPsJ2sqEt4
    secret-key: CajfY46SGJ2GNxkVK6nL6Gundlu2et
    oss:
      endpoint: oss-cn-beijing.aliyuncs.com
#
#  alibaba.cloud.access-key=your-ak
#  alibaba.cloud.secret-key=your-sk
#  alibaba.cloud.oss.endpoint=***
