spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://124.220.154.222:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 124.220.154.222:8848
    application:
      name: gulimall-auth-server
  thymeleaf:
    prefix: classpath:/templates/  #prefix：指定模板所在的目录
    check-template-location: true  #check-tempate-location: 检查模板路径是否存在
    cache: false  #cache: 是否缓存，开发模式下设置为false，避免改了模板还要重启服务器，线上设置为true，可以提高性能。
    suffix:  .html
    #encoding: UTF-8
    #content-type: text/html
    mode: HTML5
  redis:
    host: 139.9.124.79
    port: 6379


mybatis-plus:
  mapper-locations:  classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 20000


logging:
  level:
    com.atguigu.gulimall: debug

alibaba:
  cloud:
    access-key: LTAI5t9HsdbWiGnPsJ2sqEt4
    secret-key: CajfY46SGJ2GNxkVK6nL6Gundlu2et
    oss:
      endpoint: oss-cn-beijing.aliyuncs.com
#
#  alibaba.cloud.access-key=your-ak
#  alibaba.cloud.secret-key=your-sk
#  alibaba.cloud.oss.endpoint=***




