spring:
  cloud:
    nacos:
      discovery:
        server-addr: 124.220.154.222:8848
#  application:
#    name: gulimall-product
  thymeleaf:
    cache: true
  redis:
    host: 139.9.124.79
    port: 6379

server:
  port: 11000


logging:
  level:
    com.atguigu.gulimall: debug

alibaba:
  cloud:
    access-key: LTAI5t9HsdbWiGnPsJ2sqEt4
    secret-key: CajfY46SGJ2GNxkVK6nL6Gundlu2et
    oss:
      endpoint: oss-cn-beijing.aliyuncs.com
#
#  alibaba.cloud.access-key=your-ak
#  alibaba.cloud.secret-key=your-sk
#  alibaba.cloud.oss.endpoint=***


